# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tricount Clone' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tricount Clone
    pod 'Firebase/Core'
    pod 'RxFirebase/Database'
    pod 'RxFirebase/Auth'

    pod 'ObjectMapper', '~> 3.4'

end
